server:
  port: 8081
  servlet:
    context-path: /book-management-consumer

spring:
  application:
    name: dubbo-book-management-consumer

dubbo:
  registry:
    address: zookeeper://admin:password@127.0.0.1:2181

